### ISSUE TITLE
component-did-update is broken - called with some native React/JS object

### ISSUE THREAD

**Issue by dfrese** [active-group/reacl#17]
It's currently not what the docs say:

  `(component-did-update prev-app-state prev-local-state prev-arg1 prev-arg2 ...)`
  Called immediately after an update. The component can update its DOM here.

(also unclear if this is correct for app-state-free classes).
I currently need to consider changes in the args, to work around an inconvenience/bug in a third-party React component.

**Comment by neshtea** [comment]
+1
