### ISSUE TITLE
How to extract app state in an integration test?

### ISSUE THREAD

**Issue by kenranunderscore** [active-group/reacl#24]
We want (and used) to extract the app state in a test like this:

``` clj
(reacl/defclass foo this app-state []
  render
  (dom/button
   {:onclick #(reacl/send-message! this :bar)}
   "Change state")

  handle-message
  (fn [msg]
    (reacl/return :app-state msg)))

(deftest t-foo
  (let [comp (test-util/instantiate&mount foo :foo)
        btn (js/ReactTestUtils.findRenderedDOMComponentWithTag comp "button")]
    (. js/ReactTestUtils.Simulate click btn)
    (is (= (reacl/extract-app-state comp)
           :bar))))
```

With the great-rewrite, we now need an alternative to `reacl/extract-app-state` (which is for internal use only, plus it doesn't work here anymore: instead, the initial app-state `:foo` is extracted).

Maybe a whole different approach (e.g., using the `TestRenderer`) would be the solution and the above way of testing thus discouraged?

**Comment by dfrese** [comment]
There is `reacl2.test-util.alpha/extract-app-state` now, but as the package name `alpha` suggests, we also need to cleanup all those testing utilities eventually.
