### ISSUE TITLE
Html5 history and send-message!

### ISSUE THREAD

**Issue by dfrese** [active-group/reacl#27]
In some situations the handling of an action can lead to a **synchronous** browser event, in which one might want to allow `send-message!` calls, which is now forbidden (and was dangerous before).

For example, when working with the browser history, esp. via `goog.History`, one registers a `navigate` callback, which is called when the user hits 'back', but also when the application calls 'setToken', which should be used in menus and buttons to navigate to a new page, as it is then also added to the browser 'history' and allows to go back later.

So when an application has registered a callback, it will often do a `send-message!` in it:

```
(def history (goog.History.))
(event/listen history "navigate"
  (fn [e]
    (reacl/send-message! my-app [:goto-page (.-token e)])))
```

where the message leads to rendering a different content.

Now this works fine when the user hits the back button, but in menus, eventually one has to call `history.setToken`, which **synchronously** triggers that event callback. That means one could only do this directly in an event handler. But one could not do it by returning an action and handling that near the toplevel of an application - as the `send-message!` calls are prohibited there.

Now this could be solved in an application in various ways, by detecting in which context the event is triggered for example. But maybe the library could offer something for that already; there might be more situations like this.

**Comment by dfrese** [comment]
A function like this could do the trick:

```
(with-allowed-send-message!
  (fn []
    (.setToken history ...)
    (reacl/return)))
=>
(reacl/return :message [my-app [:goto-page ...]])
```

So `send-message!` call during the evaluation of the thunk would be added to the `return` value, making it a 'safe' operation again.
Although this could be wrapped around each `reduce-action`, it's probably ok to require an explicit usage of it where it is needed.

**Comment by mikesperber** [comment]
When exactly in the Reacl cycle does this happen?

My guess is that true `send-message!` can't work here, but a `queue-message!` might work, which is analogous to `(reacl/return :message ...)`.

**Comment by dfrese** [comment]
The 'navigate' event happens either
- when the user hit's "Back" in the browser,
- or the applications handles a 'goto page' action in a toplevel :reduce-action, by calling 'setToken'.

So the same code must be able to handle both cases.

**Comment by mikesperber** [comment]
Yes, but the expectation with `send-message!` is that it's synchronous - the user needs to be aware that it's not and use a different function.

**Comment by dfrese** [comment]
Added `send-message-allowed?` as a minimal api to enable working with the history in this way.

**Comment by dfrese** [comment]
So for now we leave this up to the user/user libraries to implement something for each situation where this is a problem. (there are possibilities to do it; another is turning off the callback during the 'goto page' by the application)
