### ISSUE TITLE
cljdoc API docs / badge

### ISSUE THREAD

**Issue by martinklepsch** [active-group/reacl#3]
Hey 🙂 just wanted to make you aware that there are [API docs for Reacl on cljdoc](https://cljdoc.xyz/d/reacl/reacl/CURRENT)

Feel free to use those for API docs and if you like you can also add a badge to your README:

[![cljdoc reacl badge](https://cljdoc.xyz/badge/reacl)](https://cljdoc.xyz/d/reacl/reacl/CURRENT)

```
[![cljdoc reacl badge](https://cljdoc.xyz/badge/reacl)](https://cljdoc.xyz/d/reacl/reacl/CURRENT)
```

Some older versions are [also available](https://cljdoc.xyz/d/reacl/reacl).

**Comment by dfrese** [comment]
Thanks! A "little" late, but we now use it finally.
