### ISSUE TITLE
Better error messages for local-state clause

### ISSUE THREAD

**Issue by neshtea** [active-group/reacl#40]
When defining a reacl class with a local-state, the following error produces an unhelpful error message:

```Clojure
(defclass foo this []
  local-state {:foo "bar"}
  ...)
```

Leads to

```
Could not Compile: nth not supported on this type: PersistentArrayMap
```

The error is obvious in hindsight (not using `let` syntax to create a binding), but may easily be overlooked. It should be easy to generate a better error message, for example:

```
Could not Compile: Illegal binding form in local-state clause. Hint: ...
```

Or something even more helpful.

**Comment by dfrese** [comment]
Since 2.1.2 it should be
```
  Assert failed: The local-state clause must contain exactly one binding.
```
in this case. But I can add something more for the next release (2.1.4 or 2.2).
